site_name: Wildforge Engine
site_description: Documentation for the Wildforge Engine
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

nav:
  - Home: index.md
  - Math:
      - FastNoiseLite: Math/FastNoiseLite.md
      - RectTransform: Math/RectTransform.md
  - Physics:
      - PhysicsSimulationManager: Physics/PhysicsSimulationManager.md
  - Rendering:
      - RenderPass: Rendering/RenderPass.md
      - Raytracing Renderer Roadmap: Rendering/RaytracingRendererRoadmap.md
      - Compute:
          - Compute: Rendering/Compute/Compute.md
      - Raster:
          - Raster Instance API: Rendering/Raster/RasterInstanceApi.md
      - Raytracing:
          - RaytracingAccelerationStructure: Rendering/Raytracing/RaytracingAccelerationStructure.md
          - RTMaterial: Rendering/Raytracing/RTMaterial.md
          - RTMaterialGpuBuffers: Rendering/Raytracing/RTMaterialGpuBuffers.md
          - RTMaterialStore: Rendering/Raytracing/RTMaterialStore.md
          - ShaderReflection: Rendering/Raytracing/ShaderReflection.md
      - Text:
          - RichText: Rendering/Text/RichText.md
      - UI:
          - UISprite: Rendering/UI/UISprite.md
      - Vulkan:
          - Vulkan Rendering: Rendering/Vulkan/VulkanRenderingDoc.md
  - Shader System:
      - ForgeShader: Shader/ForgeShader.md
      - ForgeShader Casting: Shader/ForgeShaderCasting.md
      - Shader Builder: Shader/ShaderBuilder.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true